### ISSUE TITLE
Remove 'with-mcrypt' - it's deprecated since PHP 7.1

### ISSUE THREAD

**Issue by wkhayrattee** [kasparsd/php-7-debian#61] opened 2018-03-11 07:51 UTC
Hi,
when compiling I get the following warning: `configure: WARNING: unrecognized options: --with-mcrypt`.

It makes sense as mcrypt is deprecated since PHP 7.1. You might want to consider removing that line.

cheers

**Comment by kasparsd** [comment] 2018-03-29 18:06
Thanks for reporting the issue @7php! This should be fixed in #56.

**Comment by kasparsd** [comment] 2018-03-29 18:07
Closing as duplicate of #55.

**Closed as completed by kasparsd** 2018-03-29 18:07 UTC
Labels: duplicate
